apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gatway-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gatway
  template:
    metadata:
      labels:
        app: api-gatway
    spec:
      containers:
        - name: api-gatway
          image: sahilgupta04/api-gatway
---
apiVersion: v1
kind: Service
metadata:
  name: api-gatway-srv
spec:
  selector:
    app: api-gatway
  ports:
    - name: api-gatway
      protocol: TCP
      port: 3000
      targetPort: 3000
